version: "3.9"

name: todo_api

services:
  api:
    build:
      context: ./todo_app
      dockerfile: Dockerfile.dev
    depends_on:
        - postgres_db
    ports:
      - "8000:8000"  # Expose container port 8000 to host port 8000  
    networks:
      - custome_network
  postgres_db:
    image: postgres:latest  # Use the official PostgreSQL image
    restart: always
    container_name: Postgres_Cont
    environment:
        - POSTGRES_USER=khalidNawaz
        - POSTGRES_PASSWORD=my_password
        - POSTGRES_DB=mydatabase
    ports:   
        - '5434:5432'
    volumes:
        - postgres_db:/var/lib/postgresql/data
    networks:
      - custome_network

volumes:
  postgres_db:
    driver: local

networks:
  custome_network:  # Define the custom network